# Based on
# https://pypi.org/project/tox-gh-actions/

---
name: Test the application using Tox.

on:
  - push
  - pull_request

jobs:
  build:
    # Using ubuntu-22.04 instead of ubuntu-latest because ubuntu-latest (24.04)
    # does not support Python 3.7. We'll upgrade to ubuntu-latest when we
    # drop support for Python 3.7 in the future.
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        django-version: ["42", "50", "51", "52"]
        exclude:
          - python-version: '3.9'
            django-version: 50
          - python-version: '3.9'
            django-version: 51
          - python-version: '3.9'
            django-version: 52
      fail-fast: false


    steps:
      - name: apt update
        run: sudo apt update
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} & Django ${{ matrix.django-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        env:
          TOXENV: django${{ matrix.django-version }}
        run: tox
